services:
  chatbox:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/chatbox"
      - "/opt/chatbox/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true